// Code generated by protoc-gen-go.
// source: chat.proto
// DO NOT EDIT!

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	chat.proto
	object.proto

It has these top-level messages:
	Chat
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Chat struct {
	Name             *string `protobuf:"bytes,1,opt" json:"Name,omitempty"`
	Text             *string `protobuf:"bytes,2,opt" json:"Text,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Chat) Reset()         { *m = Chat{} }
func (m *Chat) String() string { return proto.CompactTextString(m) }
func (*Chat) ProtoMessage()    {}

func (m *Chat) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Chat) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

func init() {
}
