// Code generated by protoc-gen-go.
// source: game.proto
// DO NOT EDIT!

package protobuf

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type GameMessage_Status int32

const (
	GameMessage_IDLE   GameMessage_Status = 0
	GameMessage_MOVING GameMessage_Status = 1
)

var GameMessage_Status_name = map[int32]string{
	0: "IDLE",
	1: "MOVING",
}
var GameMessage_Status_value = map[string]int32{
	"IDLE":   0,
	"MOVING": 1,
}

func (x GameMessage_Status) Enum() *GameMessage_Status {
	p := new(GameMessage_Status)
	*p = x
	return p
}
func (x GameMessage_Status) String() string {
	return proto.EnumName(GameMessage_Status_name, int32(x))
}
func (x *GameMessage_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GameMessage_Status_value, data, "GameMessage_Status")
	if err != nil {
		return err
	}
	*x = GameMessage_Status(value)
	return nil
}

type GameMessage struct {
	Id               *int32                `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Position         *GameMessage_Position `protobuf:"bytes,2,req,name=position" json:"position,omitempty"`
	Status           *GameMessage_Status   `protobuf:"varint,3,req,name=status,enum=protobuf.GameMessage_Status" json:"status,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *GameMessage) Reset()         { *m = GameMessage{} }
func (m *GameMessage) String() string { return proto.CompactTextString(m) }
func (*GameMessage) ProtoMessage()    {}

func (m *GameMessage) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *GameMessage) GetPosition() *GameMessage_Position {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *GameMessage) GetStatus() GameMessage_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return GameMessage_IDLE
}

type GameMessage_Position struct {
	X                *int32 `protobuf:"varint,1,req,name=x" json:"x,omitempty"`
	Y                *int32 `protobuf:"varint,2,req,name=y" json:"y,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GameMessage_Position) Reset()         { *m = GameMessage_Position{} }
func (m *GameMessage_Position) String() string { return proto.CompactTextString(m) }
func (*GameMessage_Position) ProtoMessage()    {}

func (m *GameMessage_Position) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *GameMessage_Position) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func init() {
	proto.RegisterEnum("protobuf.GameMessage_Status", GameMessage_Status_name, GameMessage_Status_value)
}
