// Code generated by protoc-gen-go.
// source: game.proto
// DO NOT EDIT!

package protobuf

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type GameMessage_Action int32

const (
	GameMessage_SPAWN  GameMessage_Action = 0
	GameMessage_IDLE   GameMessage_Action = 1
	GameMessage_MOVING GameMessage_Action = 2
)

var GameMessage_Action_name = map[int32]string{
	0: "SPAWN",
	1: "IDLE",
	2: "MOVING",
}
var GameMessage_Action_value = map[string]int32{
	"SPAWN":  0,
	"IDLE":   1,
	"MOVING": 2,
}

func (x GameMessage_Action) Enum() *GameMessage_Action {
	p := new(GameMessage_Action)
	*p = x
	return p
}
func (x GameMessage_Action) String() string {
	return proto.EnumName(GameMessage_Action_name, int32(x))
}
func (x *GameMessage_Action) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GameMessage_Action_value, data, "GameMessage_Action")
	if err != nil {
		return err
	}
	*x = GameMessage_Action(value)
	return nil
}

type GameMessage struct {
	Id               *int32                `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Position         *GameMessage_Position `protobuf:"bytes,2,req,name=position" json:"position,omitempty"`
	Action           *GameMessage_Action   `protobuf:"varint,3,req,name=action,enum=protobuf.GameMessage_Action" json:"action,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *GameMessage) Reset()         { *m = GameMessage{} }
func (m *GameMessage) String() string { return proto.CompactTextString(m) }
func (*GameMessage) ProtoMessage()    {}

func (m *GameMessage) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *GameMessage) GetPosition() *GameMessage_Position {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *GameMessage) GetAction() GameMessage_Action {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return GameMessage_SPAWN
}

type GameMessage_Position struct {
	X                *int32 `protobuf:"varint,1,req,name=x" json:"x,omitempty"`
	Y                *int32 `protobuf:"varint,2,req,name=y" json:"y,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GameMessage_Position) Reset()         { *m = GameMessage_Position{} }
func (m *GameMessage_Position) String() string { return proto.CompactTextString(m) }
func (*GameMessage_Position) ProtoMessage()    {}

func (m *GameMessage_Position) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *GameMessage_Position) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func init() {
	proto.RegisterEnum("protobuf.GameMessage_Action", GameMessage_Action_name, GameMessage_Action_value)
}
