// Code generated by protoc-gen-go.
// source: object.proto
// DO NOT EDIT!

package protobuf

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Object_Status int32

const (
	Object_IDLE   Object_Status = 0
	Object_MOVING Object_Status = 1
)

var Object_Status_name = map[int32]string{
	0: "IDLE",
	1: "MOVING",
}
var Object_Status_value = map[string]int32{
	"IDLE":   0,
	"MOVING": 1,
}

func (x Object_Status) Enum() *Object_Status {
	p := new(Object_Status)
	*p = x
	return p
}
func (x Object_Status) String() string {
	return proto.EnumName(Object_Status_name, int32(x))
}
func (x *Object_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Object_Status_value, data, "Object_Status")
	if err != nil {
		return err
	}
	*x = Object_Status(value)
	return nil
}

type Object struct {
	Id               *int32           `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Position         *Object_Position `protobuf:"bytes,2,req,name=position" json:"position,omitempty"`
	Status           *Object_Status   `protobuf:"varint,3,req,name=status,enum=protobuf.Object_Status" json:"status,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *Object) Reset()         { *m = Object{} }
func (m *Object) String() string { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()    {}

func (m *Object) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Object) GetPosition() *Object_Position {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Object) GetStatus() Object_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return Object_IDLE
}

type Object_Position struct {
	X                *int32 `protobuf:"varint,1,req,name=x" json:"x,omitempty"`
	Y                *int32 `protobuf:"varint,2,req,name=y" json:"y,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Object_Position) Reset()         { *m = Object_Position{} }
func (m *Object_Position) String() string { return proto.CompactTextString(m) }
func (*Object_Position) ProtoMessage()    {}

func (m *Object_Position) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Object_Position) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func init() {
	proto.RegisterEnum("protobuf.Object_Status", Object_Status_name, Object_Status_value)
}
